### ISSUE TITLE
install fails with obscure error message on python3

### ISSUE THREAD

**Issue by forivall** [dslackw/USBdev#1]
I didn't check the version support beforehand, and was greeted with an odd error message. Ideally, you should do a version check in the install script.
```
❯ sudo pip install USBdev --upgrade
Collecting USBdev
  Using cached USBdev-00.10.20150324.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-36_dzi2q/USBdev/setup.py", line 35, in <module>
        from usbdev.main import
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-36_dzi2q/USBdev
```

**Comment by dslackw** [comment]
Thank you very much fro report !!!

**Comment by dslackw** [comment]
Python3 not supported yet .. sorry..
